version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: isim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/isim
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - FRONTEND_URL=https://i-sim.app
      - NODE_ENV=production
      - VIRTUAL_HOST=api.i-sim.app
      - LETSENCRYPT_HOST=api.i-sim.app
      - LETSENCRYPT_EMAIL=samuel.mantilla@mail.utoronto.ca
    depends_on:
      - db
    expose:
      - "3000"
    env_file:
    - ./backend/.env.production

  ai-worker:
    build: ./ai-worker
    container_name: ai-worker
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      # - ALLOWED_ORIGINS=https://i-sim.app,https://www.i-sim.app,https://api.i-sim.app,https://ai.i-sim.app
      - VIRTUAL_HOST=ai.i-sim.app
      - LETSENCRYPT_HOST=ai.i-sim.app
      - LETSENCRYPT_EMAIL=samuel.mantilla@mail.utoronto.ca
    depends_on:
      - redis
      - backend
    expose:
      - "3001"
    command: node worker.js
    env_file:
    - ./ai-worker/.env.production

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=i-sim.app,www.i-sim.app
      - LETSENCRYPT_HOST=i-sim.app,www.i-sim.app
      - LETSENCRYPT_EMAIL=samuel.mantilla@mail.utoronto.ca
    depends_on:
      - backend
    expose:
      - "80"
    env_file:
    - ./frontend/.env.production

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - default

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - DEFAULT_EMAIL=samuel.mantilla@mail.utoronto.ca
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  pgdata:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme:
